package com.xhjsj.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AdminInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public AdminInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAIdIsNull() {
            addCriterion("a_id is null");
            return (Criteria) this;
        }

        public Criteria andAIdIsNotNull() {
            addCriterion("a_id is not null");
            return (Criteria) this;
        }

        public Criteria andAIdEqualTo(Integer value) {
            addCriterion("a_id =", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotEqualTo(Integer value) {
            addCriterion("a_id <>", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdGreaterThan(Integer value) {
            addCriterion("a_id >", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("a_id >=", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdLessThan(Integer value) {
            addCriterion("a_id <", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdLessThanOrEqualTo(Integer value) {
            addCriterion("a_id <=", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdIn(List<Integer> values) {
            addCriterion("a_id in", values, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotIn(List<Integer> values) {
            addCriterion("a_id not in", values, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdBetween(Integer value1, Integer value2) {
            addCriterion("a_id between", value1, value2, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotBetween(Integer value1, Integer value2) {
            addCriterion("a_id not between", value1, value2, "aId");
            return (Criteria) this;
        }

        public Criteria andANumberIsNull() {
            addCriterion("a_number is null");
            return (Criteria) this;
        }

        public Criteria andANumberIsNotNull() {
            addCriterion("a_number is not null");
            return (Criteria) this;
        }

        public Criteria andANumberEqualTo(String value) {
            addCriterion("a_number =", value, "aNumber");
            return (Criteria) this;
        }

        public Criteria andANumberNotEqualTo(String value) {
            addCriterion("a_number <>", value, "aNumber");
            return (Criteria) this;
        }

        public Criteria andANumberGreaterThan(String value) {
            addCriterion("a_number >", value, "aNumber");
            return (Criteria) this;
        }

        public Criteria andANumberGreaterThanOrEqualTo(String value) {
            addCriterion("a_number >=", value, "aNumber");
            return (Criteria) this;
        }

        public Criteria andANumberLessThan(String value) {
            addCriterion("a_number <", value, "aNumber");
            return (Criteria) this;
        }

        public Criteria andANumberLessThanOrEqualTo(String value) {
            addCriterion("a_number <=", value, "aNumber");
            return (Criteria) this;
        }

        public Criteria andANumberLike(String value) {
            addCriterion("a_number like", value, "aNumber");
            return (Criteria) this;
        }

        public Criteria andANumberNotLike(String value) {
            addCriterion("a_number not like", value, "aNumber");
            return (Criteria) this;
        }

        public Criteria andANumberIn(List<String> values) {
            addCriterion("a_number in", values, "aNumber");
            return (Criteria) this;
        }

        public Criteria andANumberNotIn(List<String> values) {
            addCriterion("a_number not in", values, "aNumber");
            return (Criteria) this;
        }

        public Criteria andANumberBetween(String value1, String value2) {
            addCriterion("a_number between", value1, value2, "aNumber");
            return (Criteria) this;
        }

        public Criteria andANumberNotBetween(String value1, String value2) {
            addCriterion("a_number not between", value1, value2, "aNumber");
            return (Criteria) this;
        }

        public Criteria andANameIsNull() {
            addCriterion("a_name is null");
            return (Criteria) this;
        }

        public Criteria andANameIsNotNull() {
            addCriterion("a_name is not null");
            return (Criteria) this;
        }

        public Criteria andANameEqualTo(String value) {
            addCriterion("a_name =", value, "aName");
            return (Criteria) this;
        }

        public Criteria andANameNotEqualTo(String value) {
            addCriterion("a_name <>", value, "aName");
            return (Criteria) this;
        }

        public Criteria andANameGreaterThan(String value) {
            addCriterion("a_name >", value, "aName");
            return (Criteria) this;
        }

        public Criteria andANameGreaterThanOrEqualTo(String value) {
            addCriterion("a_name >=", value, "aName");
            return (Criteria) this;
        }

        public Criteria andANameLessThan(String value) {
            addCriterion("a_name <", value, "aName");
            return (Criteria) this;
        }

        public Criteria andANameLessThanOrEqualTo(String value) {
            addCriterion("a_name <=", value, "aName");
            return (Criteria) this;
        }

        public Criteria andANameLike(String value) {
            addCriterion("a_name like", value, "aName");
            return (Criteria) this;
        }

        public Criteria andANameNotLike(String value) {
            addCriterion("a_name not like", value, "aName");
            return (Criteria) this;
        }

        public Criteria andANameIn(List<String> values) {
            addCriterion("a_name in", values, "aName");
            return (Criteria) this;
        }

        public Criteria andANameNotIn(List<String> values) {
            addCriterion("a_name not in", values, "aName");
            return (Criteria) this;
        }

        public Criteria andANameBetween(String value1, String value2) {
            addCriterion("a_name between", value1, value2, "aName");
            return (Criteria) this;
        }

        public Criteria andANameNotBetween(String value1, String value2) {
            addCriterion("a_name not between", value1, value2, "aName");
            return (Criteria) this;
        }

        public Criteria andAPassIsNull() {
            addCriterion("a_pass is null");
            return (Criteria) this;
        }

        public Criteria andAPassIsNotNull() {
            addCriterion("a_pass is not null");
            return (Criteria) this;
        }

        public Criteria andAPassEqualTo(String value) {
            addCriterion("a_pass =", value, "aPass");
            return (Criteria) this;
        }

        public Criteria andAPassNotEqualTo(String value) {
            addCriterion("a_pass <>", value, "aPass");
            return (Criteria) this;
        }

        public Criteria andAPassGreaterThan(String value) {
            addCriterion("a_pass >", value, "aPass");
            return (Criteria) this;
        }

        public Criteria andAPassGreaterThanOrEqualTo(String value) {
            addCriterion("a_pass >=", value, "aPass");
            return (Criteria) this;
        }

        public Criteria andAPassLessThan(String value) {
            addCriterion("a_pass <", value, "aPass");
            return (Criteria) this;
        }

        public Criteria andAPassLessThanOrEqualTo(String value) {
            addCriterion("a_pass <=", value, "aPass");
            return (Criteria) this;
        }

        public Criteria andAPassLike(String value) {
            addCriterion("a_pass like", value, "aPass");
            return (Criteria) this;
        }

        public Criteria andAPassNotLike(String value) {
            addCriterion("a_pass not like", value, "aPass");
            return (Criteria) this;
        }

        public Criteria andAPassIn(List<String> values) {
            addCriterion("a_pass in", values, "aPass");
            return (Criteria) this;
        }

        public Criteria andAPassNotIn(List<String> values) {
            addCriterion("a_pass not in", values, "aPass");
            return (Criteria) this;
        }

        public Criteria andAPassBetween(String value1, String value2) {
            addCriterion("a_pass between", value1, value2, "aPass");
            return (Criteria) this;
        }

        public Criteria andAPassNotBetween(String value1, String value2) {
            addCriterion("a_pass not between", value1, value2, "aPass");
            return (Criteria) this;
        }

        public Criteria andAEmailIsNull() {
            addCriterion("a_email is null");
            return (Criteria) this;
        }

        public Criteria andAEmailIsNotNull() {
            addCriterion("a_email is not null");
            return (Criteria) this;
        }

        public Criteria andAEmailEqualTo(String value) {
            addCriterion("a_email =", value, "aEmail");
            return (Criteria) this;
        }

        public Criteria andAEmailNotEqualTo(String value) {
            addCriterion("a_email <>", value, "aEmail");
            return (Criteria) this;
        }

        public Criteria andAEmailGreaterThan(String value) {
            addCriterion("a_email >", value, "aEmail");
            return (Criteria) this;
        }

        public Criteria andAEmailGreaterThanOrEqualTo(String value) {
            addCriterion("a_email >=", value, "aEmail");
            return (Criteria) this;
        }

        public Criteria andAEmailLessThan(String value) {
            addCriterion("a_email <", value, "aEmail");
            return (Criteria) this;
        }

        public Criteria andAEmailLessThanOrEqualTo(String value) {
            addCriterion("a_email <=", value, "aEmail");
            return (Criteria) this;
        }

        public Criteria andAEmailLike(String value) {
            addCriterion("a_email like", value, "aEmail");
            return (Criteria) this;
        }

        public Criteria andAEmailNotLike(String value) {
            addCriterion("a_email not like", value, "aEmail");
            return (Criteria) this;
        }

        public Criteria andAEmailIn(List<String> values) {
            addCriterion("a_email in", values, "aEmail");
            return (Criteria) this;
        }

        public Criteria andAEmailNotIn(List<String> values) {
            addCriterion("a_email not in", values, "aEmail");
            return (Criteria) this;
        }

        public Criteria andAEmailBetween(String value1, String value2) {
            addCriterion("a_email between", value1, value2, "aEmail");
            return (Criteria) this;
        }

        public Criteria andAEmailNotBetween(String value1, String value2) {
            addCriterion("a_email not between", value1, value2, "aEmail");
            return (Criteria) this;
        }

        public Criteria andARoleIsNull() {
            addCriterion("a_role is null");
            return (Criteria) this;
        }

        public Criteria andARoleIsNotNull() {
            addCriterion("a_role is not null");
            return (Criteria) this;
        }

        public Criteria andARoleEqualTo(String value) {
            addCriterion("a_role =", value, "aRole");
            return (Criteria) this;
        }

        public Criteria andARoleNotEqualTo(String value) {
            addCriterion("a_role <>", value, "aRole");
            return (Criteria) this;
        }

        public Criteria andARoleGreaterThan(String value) {
            addCriterion("a_role >", value, "aRole");
            return (Criteria) this;
        }

        public Criteria andARoleGreaterThanOrEqualTo(String value) {
            addCriterion("a_role >=", value, "aRole");
            return (Criteria) this;
        }

        public Criteria andARoleLessThan(String value) {
            addCriterion("a_role <", value, "aRole");
            return (Criteria) this;
        }

        public Criteria andARoleLessThanOrEqualTo(String value) {
            addCriterion("a_role <=", value, "aRole");
            return (Criteria) this;
        }

        public Criteria andARoleLike(String value) {
            addCriterion("a_role like", value, "aRole");
            return (Criteria) this;
        }

        public Criteria andARoleNotLike(String value) {
            addCriterion("a_role not like", value, "aRole");
            return (Criteria) this;
        }

        public Criteria andARoleIn(List<String> values) {
            addCriterion("a_role in", values, "aRole");
            return (Criteria) this;
        }

        public Criteria andARoleNotIn(List<String> values) {
            addCriterion("a_role not in", values, "aRole");
            return (Criteria) this;
        }

        public Criteria andARoleBetween(String value1, String value2) {
            addCriterion("a_role between", value1, value2, "aRole");
            return (Criteria) this;
        }

        public Criteria andARoleNotBetween(String value1, String value2) {
            addCriterion("a_role not between", value1, value2, "aRole");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andAttriText01IsNull() {
            addCriterion("attri_text01 is null");
            return (Criteria) this;
        }

        public Criteria andAttriText01IsNotNull() {
            addCriterion("attri_text01 is not null");
            return (Criteria) this;
        }

        public Criteria andAttriText01EqualTo(String value) {
            addCriterion("attri_text01 =", value, "attriText01");
            return (Criteria) this;
        }

        public Criteria andAttriText01NotEqualTo(String value) {
            addCriterion("attri_text01 <>", value, "attriText01");
            return (Criteria) this;
        }

        public Criteria andAttriText01GreaterThan(String value) {
            addCriterion("attri_text01 >", value, "attriText01");
            return (Criteria) this;
        }

        public Criteria andAttriText01GreaterThanOrEqualTo(String value) {
            addCriterion("attri_text01 >=", value, "attriText01");
            return (Criteria) this;
        }

        public Criteria andAttriText01LessThan(String value) {
            addCriterion("attri_text01 <", value, "attriText01");
            return (Criteria) this;
        }

        public Criteria andAttriText01LessThanOrEqualTo(String value) {
            addCriterion("attri_text01 <=", value, "attriText01");
            return (Criteria) this;
        }

        public Criteria andAttriText01Like(String value) {
            addCriterion("attri_text01 like", value, "attriText01");
            return (Criteria) this;
        }

        public Criteria andAttriText01NotLike(String value) {
            addCriterion("attri_text01 not like", value, "attriText01");
            return (Criteria) this;
        }

        public Criteria andAttriText01In(List<String> values) {
            addCriterion("attri_text01 in", values, "attriText01");
            return (Criteria) this;
        }

        public Criteria andAttriText01NotIn(List<String> values) {
            addCriterion("attri_text01 not in", values, "attriText01");
            return (Criteria) this;
        }

        public Criteria andAttriText01Between(String value1, String value2) {
            addCriterion("attri_text01 between", value1, value2, "attriText01");
            return (Criteria) this;
        }

        public Criteria andAttriText01NotBetween(String value1, String value2) {
            addCriterion("attri_text01 not between", value1, value2, "attriText01");
            return (Criteria) this;
        }

        public Criteria andAttriText02IsNull() {
            addCriterion("attri_text02 is null");
            return (Criteria) this;
        }

        public Criteria andAttriText02IsNotNull() {
            addCriterion("attri_text02 is not null");
            return (Criteria) this;
        }

        public Criteria andAttriText02EqualTo(String value) {
            addCriterion("attri_text02 =", value, "attriText02");
            return (Criteria) this;
        }

        public Criteria andAttriText02NotEqualTo(String value) {
            addCriterion("attri_text02 <>", value, "attriText02");
            return (Criteria) this;
        }

        public Criteria andAttriText02GreaterThan(String value) {
            addCriterion("attri_text02 >", value, "attriText02");
            return (Criteria) this;
        }

        public Criteria andAttriText02GreaterThanOrEqualTo(String value) {
            addCriterion("attri_text02 >=", value, "attriText02");
            return (Criteria) this;
        }

        public Criteria andAttriText02LessThan(String value) {
            addCriterion("attri_text02 <", value, "attriText02");
            return (Criteria) this;
        }

        public Criteria andAttriText02LessThanOrEqualTo(String value) {
            addCriterion("attri_text02 <=", value, "attriText02");
            return (Criteria) this;
        }

        public Criteria andAttriText02Like(String value) {
            addCriterion("attri_text02 like", value, "attriText02");
            return (Criteria) this;
        }

        public Criteria andAttriText02NotLike(String value) {
            addCriterion("attri_text02 not like", value, "attriText02");
            return (Criteria) this;
        }

        public Criteria andAttriText02In(List<String> values) {
            addCriterion("attri_text02 in", values, "attriText02");
            return (Criteria) this;
        }

        public Criteria andAttriText02NotIn(List<String> values) {
            addCriterion("attri_text02 not in", values, "attriText02");
            return (Criteria) this;
        }

        public Criteria andAttriText02Between(String value1, String value2) {
            addCriterion("attri_text02 between", value1, value2, "attriText02");
            return (Criteria) this;
        }

        public Criteria andAttriText02NotBetween(String value1, String value2) {
            addCriterion("attri_text02 not between", value1, value2, "attriText02");
            return (Criteria) this;
        }

        public Criteria andAttriNumber01IsNull() {
            addCriterion("attri_number01 is null");
            return (Criteria) this;
        }

        public Criteria andAttriNumber01IsNotNull() {
            addCriterion("attri_number01 is not null");
            return (Criteria) this;
        }

        public Criteria andAttriNumber01EqualTo(Integer value) {
            addCriterion("attri_number01 =", value, "attriNumber01");
            return (Criteria) this;
        }

        public Criteria andAttriNumber01NotEqualTo(Integer value) {
            addCriterion("attri_number01 <>", value, "attriNumber01");
            return (Criteria) this;
        }

        public Criteria andAttriNumber01GreaterThan(Integer value) {
            addCriterion("attri_number01 >", value, "attriNumber01");
            return (Criteria) this;
        }

        public Criteria andAttriNumber01GreaterThanOrEqualTo(Integer value) {
            addCriterion("attri_number01 >=", value, "attriNumber01");
            return (Criteria) this;
        }

        public Criteria andAttriNumber01LessThan(Integer value) {
            addCriterion("attri_number01 <", value, "attriNumber01");
            return (Criteria) this;
        }

        public Criteria andAttriNumber01LessThanOrEqualTo(Integer value) {
            addCriterion("attri_number01 <=", value, "attriNumber01");
            return (Criteria) this;
        }

        public Criteria andAttriNumber01In(List<Integer> values) {
            addCriterion("attri_number01 in", values, "attriNumber01");
            return (Criteria) this;
        }

        public Criteria andAttriNumber01NotIn(List<Integer> values) {
            addCriterion("attri_number01 not in", values, "attriNumber01");
            return (Criteria) this;
        }

        public Criteria andAttriNumber01Between(Integer value1, Integer value2) {
            addCriterion("attri_number01 between", value1, value2, "attriNumber01");
            return (Criteria) this;
        }

        public Criteria andAttriNumber01NotBetween(Integer value1, Integer value2) {
            addCriterion("attri_number01 not between", value1, value2, "attriNumber01");
            return (Criteria) this;
        }

        public Criteria andAttriNumber02IsNull() {
            addCriterion("attri_number02 is null");
            return (Criteria) this;
        }

        public Criteria andAttriNumber02IsNotNull() {
            addCriterion("attri_number02 is not null");
            return (Criteria) this;
        }

        public Criteria andAttriNumber02EqualTo(Integer value) {
            addCriterion("attri_number02 =", value, "attriNumber02");
            return (Criteria) this;
        }

        public Criteria andAttriNumber02NotEqualTo(Integer value) {
            addCriterion("attri_number02 <>", value, "attriNumber02");
            return (Criteria) this;
        }

        public Criteria andAttriNumber02GreaterThan(Integer value) {
            addCriterion("attri_number02 >", value, "attriNumber02");
            return (Criteria) this;
        }

        public Criteria andAttriNumber02GreaterThanOrEqualTo(Integer value) {
            addCriterion("attri_number02 >=", value, "attriNumber02");
            return (Criteria) this;
        }

        public Criteria andAttriNumber02LessThan(Integer value) {
            addCriterion("attri_number02 <", value, "attriNumber02");
            return (Criteria) this;
        }

        public Criteria andAttriNumber02LessThanOrEqualTo(Integer value) {
            addCriterion("attri_number02 <=", value, "attriNumber02");
            return (Criteria) this;
        }

        public Criteria andAttriNumber02In(List<Integer> values) {
            addCriterion("attri_number02 in", values, "attriNumber02");
            return (Criteria) this;
        }

        public Criteria andAttriNumber02NotIn(List<Integer> values) {
            addCriterion("attri_number02 not in", values, "attriNumber02");
            return (Criteria) this;
        }

        public Criteria andAttriNumber02Between(Integer value1, Integer value2) {
            addCriterion("attri_number02 between", value1, value2, "attriNumber02");
            return (Criteria) this;
        }

        public Criteria andAttriNumber02NotBetween(Integer value1, Integer value2) {
            addCriterion("attri_number02 not between", value1, value2, "attriNumber02");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table admin_info
     *
     * @mbggenerated do_not_delete_during_merge Sun Nov 24 14:34:09 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}