package com.xhjsj.domain;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

@Entity
@Table(name = "course_info")
public class CourseInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.id
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.c_number
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "c_number")
    private String cNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.c_name
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "c_name")
    private String cName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.c_date
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "c_date")
    private Date cDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.r_number
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "r_number")
    private String rNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.create_date
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "create_date")
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.update_date
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "update_date")
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.attri_text01
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "attri_text01")
    private String attriText01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.attri_text02
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "attri_text02")
    private String attriText02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.attri_text03
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "attri_text03")
    private String attriText03;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.attri_text04
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "attri_text04")
    private String attriText04;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.attri_number01
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "attri_number01")
    private Integer attriNumber01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.attri_number02
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "attri_number02")
    private Integer attriNumber02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course_info
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.id
     *
     * @return the value of course_info.id
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.id
     *
     * @param id the value for course_info.id
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.c_number
     *
     * @return the value of course_info.c_number
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public String getcNumber() {
        return cNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.c_number
     *
     * @param cNumber the value for course_info.c_number
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setcNumber(String cNumber) {
        this.cNumber = cNumber == null ? null : cNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.c_name
     *
     * @return the value of course_info.c_name
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.c_name
     *
     * @param cName the value for course_info.c_name
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.c_date
     *
     * @return the value of course_info.c_date
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public Date getcDate() {
        return cDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.c_date
     *
     * @param cDate the value for course_info.c_date
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setcDate(Date cDate) {
        this.cDate = cDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.r_number
     *
     * @return the value of course_info.r_number
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public String getrNumber() {
        return rNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.r_number
     *
     * @param rNumber the value for course_info.r_number
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setrNumber(String rNumber) {
        this.rNumber = rNumber == null ? null : rNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.create_date
     *
     * @return the value of course_info.create_date
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.create_date
     *
     * @param createDate the value for course_info.create_date
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.update_date
     *
     * @return the value of course_info.update_date
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.update_date
     *
     * @param updateDate the value for course_info.update_date
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.attri_text01
     *
     * @return the value of course_info.attri_text01
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public String getAttriText01() {
        return attriText01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.attri_text01
     *
     * @param attriText01 the value for course_info.attri_text01
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setAttriText01(String attriText01) {
        this.attriText01 = attriText01 == null ? null : attriText01.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.attri_text02
     *
     * @return the value of course_info.attri_text02
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public String getAttriText02() {
        return attriText02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.attri_text02
     *
     * @param attriText02 the value for course_info.attri_text02
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setAttriText02(String attriText02) {
        this.attriText02 = attriText02 == null ? null : attriText02.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.attri_text03
     *
     * @return the value of course_info.attri_text03
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public String getAttriText03() {
        return attriText03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.attri_text03
     *
     * @param attriText03 the value for course_info.attri_text03
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setAttriText03(String attriText03) {
        this.attriText03 = attriText03 == null ? null : attriText03.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.attri_text04
     *
     * @return the value of course_info.attri_text04
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public String getAttriText04() {
        return attriText04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.attri_text04
     *
     * @param attriText04 the value for course_info.attri_text04
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setAttriText04(String attriText04) {
        this.attriText04 = attriText04 == null ? null : attriText04.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.attri_number01
     *
     * @return the value of course_info.attri_number01
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public Integer getAttriNumber01() {
        return attriNumber01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.attri_number01
     *
     * @param attriNumber01 the value for course_info.attri_number01
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setAttriNumber01(Integer attriNumber01) {
        this.attriNumber01 = attriNumber01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.attri_number02
     *
     * @return the value of course_info.attri_number02
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public Integer getAttriNumber02() {
        return attriNumber02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.attri_number02
     *
     * @param attriNumber02 the value for course_info.attri_number02
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setAttriNumber02(Integer attriNumber02) {
        this.attriNumber02 = attriNumber02;
    }

    @Override
    public String toString() {
        return "CourseInfo{" +
                "id=" + id +
                ", cNumber='" + cNumber + '\'' +
                ", cName='" + cName + '\'' +
                ", cDate=" + cDate +
                ", rNumber='" + rNumber + '\'' +
                ", createDate=" + createDate +
                ", updateDate=" + updateDate +
                ", attriText01='" + attriText01 + '\'' +
                ", attriText02='" + attriText02 + '\'' +
                ", attriText03='" + attriText03 + '\'' +
                ", attriText04='" + attriText04 + '\'' +
                ", attriNumber01=" + attriNumber01 +
                ", attriNumber02=" + attriNumber02 +
                '}';
    }
}