package com.xhjsj.domain;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

@Entity
@Table(name = "experiment_info")
public class ExperimentInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_info.id
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_info.e_number
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "e_number")
    private String eNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_info.e_name
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "e_name")
    private String eName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_info.r_number
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "r_number")
    private String rNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_info.create_date
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "create_date")
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_info.update_date
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "update_date")
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_info.attri_text01
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "attri_text01")
    private String attriText01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_info.attri_text02
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "attri_text02")
    private String attriText02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_info.attri_number01
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "attri_number01")
    private Integer attriNumber01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_info.attri_number02
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "attri_number02")
    private Integer attriNumber02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table experiment_info
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_info.id
     *
     * @return the value of experiment_info.id
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_info.id
     *
     * @param id the value for experiment_info.id
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_info.e_number
     *
     * @return the value of experiment_info.e_number
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public String geteNumber() {
        return eNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_info.e_number
     *
     * @param eNumber the value for experiment_info.e_number
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void seteNumber(String eNumber) {
        this.eNumber = eNumber == null ? null : eNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_info.e_name
     *
     * @return the value of experiment_info.e_name
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public String geteName() {
        return eName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_info.e_name
     *
     * @param eName the value for experiment_info.e_name
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void seteName(String eName) {
        this.eName = eName == null ? null : eName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_info.r_number
     *
     * @return the value of experiment_info.r_number
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public String getrNumber() {
        return rNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_info.r_number
     *
     * @param rNumber the value for experiment_info.r_number
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setrNumber(String rNumber) {
        this.rNumber = rNumber == null ? null : rNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_info.create_date
     *
     * @return the value of experiment_info.create_date
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_info.create_date
     *
     * @param createDate the value for experiment_info.create_date
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_info.update_date
     *
     * @return the value of experiment_info.update_date
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_info.update_date
     *
     * @param updateDate the value for experiment_info.update_date
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_info.attri_text01
     *
     * @return the value of experiment_info.attri_text01
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public String getAttriText01() {
        return attriText01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_info.attri_text01
     *
     * @param attriText01 the value for experiment_info.attri_text01
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setAttriText01(String attriText01) {
        this.attriText01 = attriText01 == null ? null : attriText01.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_info.attri_text02
     *
     * @return the value of experiment_info.attri_text02
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public String getAttriText02() {
        return attriText02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_info.attri_text02
     *
     * @param attriText02 the value for experiment_info.attri_text02
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setAttriText02(String attriText02) {
        this.attriText02 = attriText02 == null ? null : attriText02.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_info.attri_number01
     *
     * @return the value of experiment_info.attri_number01
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public Integer getAttriNumber01() {
        return attriNumber01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_info.attri_number01
     *
     * @param attriNumber01 the value for experiment_info.attri_number01
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setAttriNumber01(Integer attriNumber01) {
        this.attriNumber01 = attriNumber01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_info.attri_number02
     *
     * @return the value of experiment_info.attri_number02
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public Integer getAttriNumber02() {
        return attriNumber02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_info.attri_number02
     *
     * @param attriNumber02 the value for experiment_info.attri_number02
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setAttriNumber02(Integer attriNumber02) {
        this.attriNumber02 = attriNumber02;
    }
}