package com.xhjsj.domain;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

@Entity
@Table(name = "student_info")
@ApiModel(description = "学生信息表单")
public class StudentInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.s_id
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "s_id")
    private Integer sId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.s_number
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "s_number")
    @ApiModelProperty(value = "学号", name = "sNumber", required = true, example = "201903211004")
    private String sNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.s_name
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "s_name")
    @ApiModelProperty(value = "姓名", name = "sName", required = true, example = "张三")
    private String sName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.s_pass
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "s_pass")
    private String sPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.s_major
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "s_major")
    @ApiModelProperty(value = "专业", name = "sMajor", required = true, example = "计算机科学与技术")
    private String sMajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.s_email
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "s_email")
    private String sEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.s_role
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "s_role")
    private String sRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.create_date
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "create_date")
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.update_date
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "update_date")
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.attri_text01
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "attri_text01")
    private String attriText01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.attri_text02
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "attri_text02")
    private String attriText02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.attri_number01
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "attri_number01")
    private Integer attriNumber01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.attri_number02
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    @Column(name = "attri_number02")
    private Integer attriNumber02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student_info
     *
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.s_id
     *
     * @return the value of student_info.s_id
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.s_id
     *
     * @param sId the value for student_info.s_id
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.s_number
     *
     * @return the value of student_info.s_number
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public String getsNumber() {
        return sNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.s_number
     *
     * @param sNumber the value for student_info.s_number
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setsNumber(String sNumber) {
        this.sNumber = sNumber == null ? null : sNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.s_name
     *
     * @return the value of student_info.s_name
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.s_name
     *
     * @param sName the value for student_info.s_name
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.s_pass
     *
     * @return the value of student_info.s_pass
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public String getsPass() {
        return sPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.s_pass
     *
     * @param sPass the value for student_info.s_pass
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setsPass(String sPass) {
        this.sPass = sPass == null ? null : sPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.s_major
     *
     * @return the value of student_info.s_major
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public String getsMajor() {
        return sMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.s_major
     *
     * @param sMajor the value for student_info.s_major
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setsMajor(String sMajor) {
        this.sMajor = sMajor == null ? null : sMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.s_email
     *
     * @return the value of student_info.s_email
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public String getsEmail() {
        return sEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.s_email
     *
     * @param sEmail the value for student_info.s_email
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setsEmail(String sEmail) {
        this.sEmail = sEmail == null ? null : sEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.s_role
     *
     * @return the value of student_info.s_role
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public String getsRole() {
        return sRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.s_role
     *
     * @param sRole the value for student_info.s_role
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setsRole(String sRole) {
        this.sRole = sRole == null ? null : sRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.create_date
     *
     * @return the value of student_info.create_date
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.create_date
     *
     * @param createDate the value for student_info.create_date
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.update_date
     *
     * @return the value of student_info.update_date
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    @Override
    public String toString() {
        return "StudentInfo{" +
                "sId=" + sId +
                ", sNumber='" + sNumber + '\'' +
                ", sName='" + sName + '\'' +
                ", sPass='" + sPass + '\'' +
                ", sMajor='" + sMajor + '\'' +
                ", sEmail='" + sEmail + '\'' +
                ", sRole='" + sRole + '\'' +
                ", createDate=" + createDate +
                ", updateDate=" + updateDate +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.update_date
     *
     * @param updateDate the value for student_info.update_date
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.attri_text01
     *
     * @return the value of student_info.attri_text01
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public String getAttriText01() {
        return attriText01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.attri_text01
     *
     * @param attriText01 the value for student_info.attri_text01
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setAttriText01(String attriText01) {
        this.attriText01 = attriText01 == null ? null : attriText01.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.attri_text02
     *
     * @return the value of student_info.attri_text02
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public String getAttriText02() {
        return attriText02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.attri_text02
     *
     * @param attriText02 the value for student_info.attri_text02
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setAttriText02(String attriText02) {
        this.attriText02 = attriText02 == null ? null : attriText02.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.attri_number01
     *
     * @return the value of student_info.attri_number01
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public Integer getAttriNumber01() {
        return attriNumber01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.attri_number01
     *
     * @param attriNumber01 the value for student_info.attri_number01
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setAttriNumber01(Integer attriNumber01) {
        this.attriNumber01 = attriNumber01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.attri_number02
     *
     * @return the value of student_info.attri_number02
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public Integer getAttriNumber02() {
        return attriNumber02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.attri_number02
     *
     * @param attriNumber02 the value for student_info.attri_number02
     * @mbggenerated Sun Nov 24 14:34:09 CST 2019
     */
    public void setAttriNumber02(Integer attriNumber02) {
        this.attriNumber02 = attriNumber02;
    }
}