package com.xhjsj.mapper;

import com.xhjsj.domain.AdminInfo;
import com.xhjsj.domain.AdminInfoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface AdminInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    int countByExample(AdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    int deleteByExample(AdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    int deleteByPrimaryKey(Integer aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    int insert(AdminInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    int insertSelective(AdminInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    List<AdminInfo> selectByExample(AdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    AdminInfo selectByPrimaryKey(Integer aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") AdminInfo record, @Param("example") AdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    int updateByExample(@Param("record") AdminInfo record, @Param("example") AdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    int updateByPrimaryKeySelective(AdminInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    int updateByPrimaryKey(AdminInfo record);
}