package com.xhjsj.mapper;

import com.xhjsj.domain.CourseInfo;
import com.xhjsj.domain.CourseInfoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface CourseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    int countByExample(CourseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    int deleteByExample(CourseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    int insert(CourseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    int insertSelective(CourseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    List<CourseInfo> selectByExample(CourseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") CourseInfo record, @Param("example") CourseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    int updateByExample(@Param("record") CourseInfo record, @Param("example") CourseInfoExample example);
}