package com.xhjsj.mapper;

import com.xhjsj.domain.ExperimentInfo;
import com.xhjsj.domain.ExperimentInfoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ExperimentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experiment_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    int countByExample(ExperimentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experiment_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    int deleteByExample(ExperimentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experiment_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experiment_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    int insert(ExperimentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experiment_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    int insertSelective(ExperimentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experiment_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    List<ExperimentInfo> selectByExample(ExperimentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experiment_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    ExperimentInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experiment_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") ExperimentInfo record, @Param("example") ExperimentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experiment_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    int updateByExample(@Param("record") ExperimentInfo record, @Param("example") ExperimentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experiment_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    int updateByPrimaryKeySelective(ExperimentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experiment_info
     *
     * @mbggenerated Sun Nov 17 15:05:10 CST 2019
     */
    int updateByPrimaryKey(ExperimentInfo record);
}